# Numpy is used for creating arrays and scietific Computing

In [1]:
import numpy as np

In [2]:
# One dimensional Array
n1 = np.array([10,20,30,40])


In [3]:
n1

array([10, 20, 30, 40])

In [4]:
n2 = np.array([[11,12,13,14,15]])

In [5]:
n2

array([[11, 12, 13, 14, 15]])

In [6]:
# Initializing Numpy in different ways
# Initializing with Zero
n3 = np.zeros((1,2))

In [7]:
n3

array([[0., 0.]])

In [8]:
n4= np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# Initializing numpy with same number
n5 = np.full((2,2),10)
n5

array([[10, 10],
       [10, 10]])

In [10]:
#Initializing Numpy with a range 
n6 = np.arange(12,34)

In [11]:
n6

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33])

In [12]:
n7 = np.arange(1,50,4)

In [13]:
n7

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49])

In [14]:
# Initializing Numpy with Random numbers
n8 = np.random.randint(10,500,10)

In [15]:
n8

array([ 99, 222, 312,  88,  52, 209, 137, 333, 479, 163])

In [16]:
# checking the shape of Numpy Array


In [17]:
n9 = np.array([[11,12,13,14,15]])
n9.shape

(1, 5)

In [18]:
# Joining Numpy Array
# vstack() - Vertical Stacking 
n10 = np.array([1,2,3,4,5])
n11 = np.array([6,7,8,9,10])

np.vstack((n10,n11))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
# Joining Numpy Array
# hstack() - Horizontal Stacking 
n12 = np.array([10,20,30,40,50])
n13 = np.array([60,70,80,90,100])

np.hstack((n12,n13))

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [20]:
# Joining Numpy Array
# cstack() - Column Stacking 
n14 = np.array([10,20,30,40,50])
n15 = np.array([60,70,80,90,100])

np.column_stack((n14,n15))

array([[ 10,  60],
       [ 20,  70],
       [ 30,  80],
       [ 40,  90],
       [ 50, 100]])

In [21]:
# Numpy insertion & Difference
n14 = np.array([10,20,30,40,50])
n15 = np.array([60,20,30,70,80,90])



In [22]:
np.intersect1d(n14,n15) # Common Elements

array([20, 30])

In [23]:
np.setdiff1d(n15,n14) # shows differnce between two list

array([60, 70, 80, 90])

In [24]:
# Adding Numpy Arrays
 
n16 = np.array([12,34])
n17 = np.array([23,56])

np.sum([n16,n17])


125

In [25]:
# NUmpy Basic Addition
new1 = np.array([10,20,30,40])

new1=new1+1
new1

array([11, 21, 31, 41])

In [26]:
# NUmpy Basic Subrtaction
new2 = np.array([10,20,30,40])

new2=new2-3
new2

array([ 7, 17, 27, 37])

In [27]:
# NUmpy Basic MUltiplication
new3 = np.array([10,20,30,40])

new3=new2*3
new3

array([ 21,  51,  81, 111])

In [28]:
# NUmpy Basic division
new4 = np.array([10,20,30,40])

new4=new4/3
new4

array([ 3.33333333,  6.66666667, 10.        , 13.33333333])

In [34]:
# Mean
no1 = np.array([12,23,45,34,56,78,90])

np.mean(no1)



48.285714285714285

In [33]:
np.median(no1)

45.0

In [32]:
np.std(no1)

26.331481894787277

In [49]:
#Numpy Matrix
np1 = np.array([[12,13,14,15],[16,17,18,19],[20,21,22,23]])

In [48]:
np1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
np1.mean()


17.5

In [41]:
np1.shape


(3, 4)

In [42]:
np1.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [43]:
np1.all()

True

In [44]:
np1.sum()

210

In [45]:
np1[0]

array([12, 13, 14, 15])

In [52]:
np1[:,1]

array([13, 17, 21])

In [53]:
 np1.T

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23]])

In [58]:
#Matrix Multiplication

a1 = np.array([[1,3,0],[5,6,7],[12,9,10]])

a2 = np.array([[1,2,5],[2,1,7],[6,7,10]])

a1.dot(a2)
a2.dot(a1)

array([[ 71,  60,  64],
       [ 91,  75,  77],
       [161, 150, 149]])

In [59]:
# Saving Numpy
sa = np.array([[1,2,5],[2,1,7],[6,7,10]])
np.save('my_numpy_saved',sa)

In [60]:
# Loading Numpy
sa2 = np.load('my_numpy_saved.npy')

In [61]:
sa2

array([[ 1,  2,  5],
       [ 2,  1,  7],
       [ 6,  7, 10]])